### ISSUE TITLE
Dialogue response options cut off on left side of screen

### ISSUE THREAD

**Issue by bcolema61** [Althro/Tinvaak#5]
**Upload your crashlog**

_No crash._

**Required: Modlist.txt**

[modlist.txt](https://github.com/Althro/Tinvaak/files/6332973/modlist.txt)

**Describe the bug**

_When offered a dialogue response, the dialogue options are cut off on the left side of the screen so I am unable to read the first half of each option._

**To Reproduce**

_Speak to anyone with a dialogue response option._

**Expected behavior**

_The dialogue options should appear somewhere more intuitive, likely the middle of the screen?_

**Screenshots**

_I don't know what mod is blocking it, but screenshots are impossible to be saved.  It shows a screenshot is being saved, but I've spent the last hour and a half scouring my computer for the file, and no matter how many I take, it doesn't exist.  I can't paste the image into paint or anything either.  So you're going to have to take my word for it._

_I did nothing special outside of the instructions you gave.  The problem was there by default.  I created a second character to start from scratch and see if I missed something, and the issue remains._

**Modlist version**

_Tinvaak._

**Did you add any additional mods?**

_No._

**Comment by Althro** [comment]
If you're using an ultra-wide or monitor of different resolution to 16:9, you will need to re-install the mod called "Dialogue interface reshaped" and select the resoultion your monitor is. Screenshots not being saved is a known issue. This can be fixed by downloading these files and pasting them into the following folder: _PathtoTinvaak_/Tinvaak/profiles/Tinvaak. The "pathto" is where you have the list installed.

[Replacement Ini Files.zip](https://github.com/Althro/Tinvaak/files/6335378/Replacement.Ini.Files.zip)

**Comment by Althro** [comment]
I've now updated the readme to add in the part about reinstalling Dialogue Interface reshaped.

**Comment by bcolema61** [comment]
Thank you!  I reinstalled Dialogue Interface Reshaped and all is working.  I'm using 1920x1200 so I didn't really follow the ultra-wide section.  It is good now though, thank you!

**Comment by Althro** [comment]
No worries 😄
